[tasks.build]
install_crate = { crate_name = "cross", binary = "cross", test_arg = "--help" }
command = "cross"
args = ["build", "--target=arm-unknown-linux-gnueabihf"]
dependencies = ["format"]

[tasks.build-release]
install_crate = { crate_name = "cross", binary = "cross", test_arg = "--help" }
command = "cross"
args = ["build", "--target=arm-unknown-linux-gnueabihf", "--release"]
dependencies = ["format"]