[tasks.wasm-pack-build]
description = "Run wasm-pack build command."
extend = "wasm-pack-base"
args = ["build", "@@split(CARGO_MAKE_WASM_BUILD_ARGS, )"]

[tasks.build]
clear = true
env = { "CARGO_MAKE_WASM_BUILD_ARGS" = "--target web --out-name nightpi --dev" }
run_task = "wasm-pack-build"

[tasks.build-release]
clear = true
env = { "CARGO_MAKE_WASM_BUILD_ARGS" = "--target web --out-name nightpi" }
run_task = "wasm-pack-build"